name: spatial-econ-cnn
channels:
    - conda-forge
dependencies:
  - python=3.8
  - tensorflow=2.7.0
  - numpy=1.22.3
  - hdf5=1.8.15
  - numexpr=2.8.1
  - cython=0.29.28
  - c-blosc2=2.0.4
  - pytables=3.7.0
  - pydrive=1.3.1
  - pandas=1.4.2
  - tqdm=4.64.0